# Generated by Django 2.2 on 2019-05-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatPetGender',
            fields=[
                ('gender_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('gender_desc', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CatPetSpecies',
            fields=[
                ('species_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('species_desc', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CatUserOwner',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatUserVet',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnerData',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('first_last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('profile_img', models.CharField(max_length=512, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='helpet_api.CatUserOwner')),
            ],
        ),
        migrations.CreateModel(
            name='UserVetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpet_api.CatUserVet')),
            ],
        ),
        migrations.CreateModel(
            name='CatPet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpet_api.CatPetGender')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpet_api.CatPetSpecies')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpet_api.CatUserOwner')),
            ],
        ),
    ]
